# tasks for Debian Familly
---
- name: PXC | Update cache
  apt:
    update_cache: yes
  changed_when: false

- name: PXC | Install Percona repo
  apt:
    deb: "{{ xtradb_repo_deb_url }}"

- name: PXC | Update cache
  apt:
    update_cache: yes
  changed_when: false
...
